# ----
# Site

title: Forschungsgruppe Neuropsychologie - Zaehlelab
url: https://zaehlelab.org
baseurl: https://zaehlelab.org
google_analytics_key:
google_maps_javascript_api_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/favicon.png
tagline: Die Internetpr채senz der Forschungsgruppe Neuropsychologie (Zaehlelab) an der Klinik f체r Neurologie des Universit채tsklinikums Magdeburg.
description: Die Forschungsgruppe Neuropsychologie (Zaehlelab) unter der Leitung von PD Dr. Tino Z채hle untersucht die Effekte non-invasiver und invasiver Elektrostimuation des menschlichen Gehirns.
author:
  name: Stefan Repplinger
  email:
  twitter: stfnrpplngr
social:
  name: Forschungsgruppe Neuropsychologie
  links:
    - https://zaehlelab.org

# -----
# Build
highlighter: rouge

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  funding_members:
    _hide_content: true
  alumni_members:
    _hide_content: true
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"

# -----------
# CloudCannon

social_icons:
#  - Facebook
#  - Google Plus
#  - Instagram
#  - LinkedIn
#  - Pinterest
#  - Tumblr
#  - Twitter
#  - YouTube
#  - Email
#  - RSS

_comments:
  description: Forschungsgruppe Neuropsychologie - Zaehlelab
  blurb: Forschungsgruppe Neuropsychologie - Zaehlelab


plugins:
  - jekyll-seo-tag
